import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        // Terra State brand colors (direct access)
        crimson: {
          DEFAULT: "#7A1022",
          50: "#FDF2F4",
          100: "#FAE5E9",
          200: "#F5CCD3",
          300: "#EDA2AE",
          400: "#E06F82",
          500: "#CF4059",
          600: "#B52742",
          700: "#7A1022",
          800: "#6B0E1E",
          900: "#5A0C19",
          950: "#33060E",
        },
        gold: {
          DEFAULT: "#A0834A",
          50: "#FAF6EF",
          100: "#F3EADB",
          200: "#E6D4B5",
          300: "#D5B888",
          400: "#C49E64",
          500: "#A0834A",
          600: "#8A6E3D",
          700: "#6E5732",
          800: "#5C482C",
          900: "#4E3D28",
          950: "#2C2014",
        },
        teal: {
          DEFAULT: "#3D6B5E",
          50: "#F0F7F5",
          100: "#DCEDE7",
          200: "#BBD9D0",
          300: "#8FBFB2",
          400: "#639E8E",
          500: "#3D6B5E",
          600: "#36604F",
          700: "#2E4F42",
          800: "#284037",
          900: "#23362F",
          950: "#131E1A",
        },
        sage: {
          DEFAULT: "#6B7F5B",
          50: "#F4F6F1",
          100: "#E6EBE0",
          200: "#CED8C3",
          300: "#AEBE9D",
          400: "#8DA17A",
          500: "#6B7F5B",
          600: "#556647",
          700: "#434F38",
          800: "#37402F",
          900: "#2F3629",
          950: "#171C14",
        },
        cream: {
          DEFAULT: "#F0EDE6",
          50: "#FAFAF8",
          100: "#F5F3EF",
          200: "#F0EDE6",
          300: "#E0DAC9",
          400: "#CEC4AB",
          500: "#BBAD8D",
          600: "#AB9A75",
          700: "#968362",
          800: "#7B6C53",
          900: "#655845",
          950: "#352E23",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
